theme: jekyll-theme-cayman
title: "Carbon Free Footprint Project"
tagline: "An analysis designed to establish a Carbon Free Footprint when operating a BC Northern Lights Bloombox 'Full Blast' 24/7"
description: "An analysis designed to establish a Carbon Free Footprint when operating a BC Northern Lights Bloombox 'Full Blast' 24/7"
author:
    name: "Robert Weber, Director"
    email: "mminail@icloud.com"
    github: "mminail"
    twitter: "mminail"
baseurl: "/"
exclude: ['README.md']
markdown: kramdown
highlighter: rouge
kramdown:
    input: "GFM"
    hard_wrap: "false"
    syntax_highlighter: "rouge"
timezone: "America/Phoenix"
google_analytics: [UA-44765001-8]
defaults:
  - scope:
      path: "assets/img"
    values:
      image: "true"
defaults:
  - scope:
      path: "" 
      type: "pages"
    values:
      layout: "alt-default"
      author: "Robert Weber, Director"
collections:
  collection_CFFP:
    output: "true"
defaults:
  - scope:
      path: ""
      type: "collection_CFFP"
    values:
      layout: "page"
defaults:
  - scope:
      path: "/docs/pages"
      type: "pages"
    values:
      layout: "alt-default" 
      author: "Robert Weber, Director"
github: [metadata]
